# Основная конфигурация
App:
  SessionTimeout: 14400
  TimeZone: "Europe/Moscow"
  Mode: "dev"
  Version: "1.1.1"

Lg:
  Info: true
  Notice: true
  Warning: true
  Error: true
  Critical: true
  Fatal: true
  Traces: true
  OutStd: true
  OutFile: ""
  OutHttp: ""

Workflow:
  Limitch: 1000      # буфер канала задач
  Limitpool: 9       # максимальное количество воркеров обслуживающих задачи

Http:
  Proto: "http"
  Host: "localhost"
  Port: 8080
  WriteTimeout: 10  # Время ожидания окончания передачи ответа в секундах, по истечении которого соединение сбрасывается
  ReadTimeout: 10   # Время ожидания web запроса в секундах, по истечении которого соединение сбрасывается
  MaxHeaderBytes: 1048576 # Максимальный размер заголовка получаемого от браузера клиента в байтах
  Proxy: "" # format: "http://login:pass@bproxy.msk.mts.ru:3131"
  Cors:
    Use: true
    AllowedOrigins: ["*"]
    AllowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    AllowedHeaders: ["Accept", "Authorization", "Content-Type", "X-CSRF-Token"]
    ExposedHeaders: ["Link"]
    AllowCredentials: true
    MaxAge: 300

Connect:
  Mysql:
    Host: "" # tcp(localhost:3306)
    Name: "accounter"
    Login: "root"
    Password: "root"
    Charset: "utf8"
  Postgresql:
    Host: "localhost" # localhost
    Port: 5432
    Name: "test"
    Login: "postgres"
    Password: "postgres"
    Ssl: "disable"
    Charset: "utf8"

Sample:
  Name: "Vasya Pupkin"
  IsAccess: true
  Balance: 65.789
